spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3308/laravel?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Chongqing&useSSL=true
      username: py
      password: 123
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
logging:
  level:
    org.py.sweb.mapper: debug
mapper:
  identity: mysql
page_limit: 5
mybatis:
  configuration:
    map-underscore-to-camel-case: true
allowImgs: .PNG .BMP .JPG .JPEG .GIF .TIFF .DIB .ICO .TIF .HEIC
uploadDir: upfiles